# action.yml
name: 'Install Python'
description: 'Install a specific version of Python'
inputs:
  python-version:
    description: 'Version of Python to install'
    required: true
runs:
  using: 'bash'
  shell: 'bash'
  main: './install-python.sh'
