# action.yml
name: 'Install Python'
description: 'Install a specific version of Python'
inputs:
  python-version:
    description: 'Version of Python to install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Set up Python'
       run: |
             apt-get update -y && apt-get install python3.9 -y
             python3 --version
