# .github/actions/install-python-3.12/action.yml
name: 'Install Python 3.12'
description: 'Install Python 3.12'

runs:
  using: 'composite'
  steps:
    - name: 'Set up Python 3.12'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.12

  - name: 'Show Python Version'
    run: python3.12 --version
