# action.yml
name: 'Install Python'
description: 'Install a specific version of Python'
inputs:
  python-version:
    description: 'Version of Python to install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Set up Python'
      run: |
      
           bash install-python.sh ${{ inputs.python-version }}
        # chmod +x Maxwell134/Docker_login_actions/install-python.sh
        # Maxwell134/Docker_login_actions/install-python.sh ${{ inputs.python-version }}
      shell: bash
