# action.yml
name: 'Install Python'
description: 'Install a specific version of Python'
inputs:
  python-version:
    description: 'Version of Python to install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Set up Python'
      run: |
        chmod +x script.sh
        ./script.sh ${{ inputs.python-version }}
      shell: bash

    - name: 'Run'
      run: python3 repo.py
