name: 'Simple Hello Action'
description: 'Prints a greeting with a customizable name'

inputs:
  myName:
    description: 'The name for the greeting'
    required: true

runs-on: ubuntu-latest

runs:
  using: 'docker'
  image: 'alpine:latest'
  entrypoint: '/bin/sh'
  script: |
    echo "Hello, ${{ inputs.myName }}"

# steps:
#   - name: Run Simple Hello Action
#     run: echo "Hello"
