# action.yml
name: 'Install Python'
description: 'Install a specific version of Python'
inputs:
  python-version:
    description: 'Version of Python to install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Set up Python'
       entrypoint: ./install-python.sh ${{ inputs.python-version }}
